### ISSUE TITLE
Consider a more permissive license?

### ISSUE THREAD

**Issue by Boscop** [dmnsafonov/boolean-enums#2]
Would you consider using a more permissive license, that's more compatible with other crates in the ecosystem, e.g. MIT or Apache? :)

**Comment by domisafonova** [comment]
I just realized that LGPL is not doing what I thought it would.  The requirement of a way to relink with the library practically makes it full-blown GPL 3 for the crate.
Now, I want to re-license it, but there is another contributor there.  Is it enough to just email them for permission?

**Comment by Boscop** [comment]
Yes

**Comment by dtolnay** [comment]
I agree to relicense my contributions as dual MIT/Apache-2.0. Thanks for checking!

**Comment by domisafonova** [comment]
Done.
